### PR TITLE
Update full_generation.md

### PR DESCRIPTION
**Pull request by markmrets**
added the generation adjustments article to this section

### CODE REVIEW

**Review by BryanGower — CHANGES_REQUESTED** [review]
Update links: 
https://mrets.github.io/Help/Generation%20Adjustments
https://mrets.github.io/Help/SPP
https://mrets.github.io/Help/MISO

**Comment by BryanGower** [comment]
@markmrets update these links.

**Review by markmrets — COMMENTED** [review]
fixed links

**Review by markmrets — COMMENTED** [review]
fixed links

**Review by BryanGower — APPROVED** [review]

**Pull request merged**
